# vim: set ft=fish :et"

complete -c 'arson' -s 'D' -l 'Download' -x -d "Download the AUR package specified"
complete -c 'arson' -s 'S' -l 'Search' -x -d "Search AUR for a package name"
complete -c 'arson' -s 'I' -l 'Info' -x -d "Get information about a package"
complete -c 'arson' -s 'U' -l 'Upgrade' -A -d "List of foreign packages which have an update available for them in AUR"
complete -c 'arson' -l 'save-to' -n '__fish_contains_opt -s D Download' -r -d "Directory for arson to download AUR packages [Default: Current directory]"
complete -c 'arson' -s 'k' -l 'keep' -n '__fish_contains_opt -s D Download' -d "Keep the .tar.gz after extracting it [Default: Delete]"
complete -c 'arson' -s 'f' -l 'force' -n '__fish_contains_opt -s D Download' -d "Force the extraction of the package"
complete -c 'arson' -s 'v' -l "verbose" -d "Run verbosely"
complete -c 'arson' -s 'c' -l 'no'-color -d "Supress color output [Default: No]"
complete -c 'arson' -s 'V' -l 'version' -d "Display the version number"
complete -c 'arson' -s 'h' -l 'help' -d "Display the help message"
complete -c 'arson' -l 'more-help' -d "Display even more help"
