## arg 1:  the new package version
post_install() {
  echo ">> Installing JSON and Facets ruby gems, this could take a while..."
  gem install --remote json facets
}

post_upgrade() {
  echo ">> Make sure the JSON and Facets ruby gems are up to date"
  echo ">> See arson --more-help for help"
}

post_remove() {
  echo ">> The JSON and Facets ruby gems are still installed on your system, if you want to remove them, run 'gem uninstall json facets'"
}

# vim:set ts=2 sw=2 et:
